### PR TITLE
adds default lat+long values and removes unnecessary else statement

### PR DESCRIPTION
**Pull request by collinjensen**
# Description

Adds default latitude and longitude values that point to a Family Promise homeless shelter in Spokane, WA. Also removes unnecessary else statement. [Video](https://youtu.be/P0FZovPZvPA)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Change status
- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

Tested using postman and validated that the new default value is being returned properly.

# Checklist:

- [x] I have pulled from main before submitting this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by mramputatoes** [comment]
Simple and makes a lot of sense to have it default to a place of operation for Family Promise.

**Review by ebnersam — APPROVED** [review]
Really good idea having it default to a shelter, looks like a good, simple, and clear change to me.

**Review by santorap — APPROVED** [review]
The change makes sense to me. Getting rid of the else statement is likely cleaner, at least for now.

My only question would be confirming that GeoPy will degrade gracefully if the only value passed into it from `address_string` is a zip code and still spit out valid lat/long coordinates.

**Comment by collinjensen** [comment]
> The change makes sense to me. Getting rid of the else statement is likely cleaner, at least for now.
> 
> My only question would be confirming that GeoPy will degrade gracefully if the only value passed into it from `address_string` is a zip code and that it will still output valid lat/long coordinates in that case.

Yes, that is exactly how geopy would act. It degrades very gracefully.

**Pull request merged**
