### PR TITLE
updated and deployed new version number as demo

### PR DESCRIPTION
**Pull request by collinjensen**
# Description

updated version number (in main.py) from 0.37.2 -> 0.38.01 to demonstrate deploying a change to AWS. Video [here](https://youtu.be/b0bESoYx0J0)

## Type of change

- [x] This change requires a documentation update

## Change status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

No testing needed.

# Checklist:

- [x] I have pulled from master before submitting this PR
- [x] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by sntemple12 — APPROVED** [review]
Walked several others through the process of deploying to aws. Good job on breaking apart everything for others to understand. This is just a change I watched you do during zoom.

**Review by ebnersam — APPROVED** [review]
Thanks again for the live demo, Collin.

**Review by santorap — APPROVED** [review]
Simple update. Every time a new deployment is made to AWS/EB, the version number needs to be incremented. Great job on the new `/geocode/` endpoint!

**Comment by collinjensen** [comment]
Video [here](https://youtu.be/b0bESoYx0J0) if anyone wants to watch nothing for about 30 seconds

**Comment by mramputatoes** [comment]
Simple and clean. Quick video explaining what you did.

**Pull request merged**
