### PR TITLE
Added new metric endpoints for various metrics

### PR DESCRIPTION
**Pull request by ebnersam**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Added 6 new metric endpoints based on Trello card for metrics.
https://www.loom.com/share/12ba434186da47f69d5ed0db492829d1

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change status
- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Ran app locally and tested each endpoint. All endpoints are functional and output expected values.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by sntemple12** [comment]
I think this is a great start to the building of the metrics for the dashboard when they are ready to bring that on. This can also be the foundation for building the future metrics and visualizations.

**Review by sntemple12 — APPROVED** [review]
See comment below

**Review by santorap — APPROVED** [review]
Great start on these metrics!

**Comment by mramputatoes** [comment]
Looks great! Helps build out a foundation for further visualizations and reports.

**Review by collinjensen — APPROVED** [review]
The new endpoints follow the same formatting as previous ones- love that. I would like to have seen more of your progression in the commit history. A single commit with ALL the changes makes it harder to see what was being worked on.

**Pull request merged**
