### PR TITLE
updated README to include contributors Collin, Jeremiah, Paul, Sam Ebner, and Samantha Temple

### PR DESCRIPTION
**Pull request by collinjensen**
# Description

All I've added in this pull request is a "Contributors" section to the bottom of the readme. No other changes have been made.
VIDEO HERE: https://www.youtube.com/watch?v=V5qsVJ-uKkY

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change status
- [x ] Complete, tested, ready to review and merge

# How Has This Been Tested?

I tested to ensure GitHub will render the markdown the way I expect by uploading it to a personal repo. It looks great!

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x ] I have pulled from master before submitting this PR
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

### CODE REVIEW

**Comment by mramputatoes** [comment]
Looks good, each link is correct.

**Comment by sntemple12** [comment]
I think it's a nice update to the read me and practice doing your first pull-request. I approve of this change.

**Comment by santorap** [comment]
Any reason @sntemple12 isn't in here too?

**Comment by ebnersam** [comment]
Looks good Collin, I'm unsure if Samantha is to be included under contributors here or left out as you did. Other than that it looks great

**Review by ebnersam — APPROVED** [review]

**Review by sntemple12 — CHANGES_REQUESTED** [review]
Please add Samantha Temple to the updated ReadMe.

**Comment by collinjensen** [comment]
> Please add Samantha Temple to the updated ReadMe.

Samantha Temple has been added with new commit.

**Review by sntemple12 — APPROVED** [review]
Thank you for the addition!

**Review by ashtilawat23 — APPROVED** [review]

**Pull request merged**
