### PR TITLE
updated api version & changed veteran_counts function to post

### PR DESCRIPTION
**Pull request by keilayb**
# Description

We were asked to update the version of the API and to fix the description, as well as, add a .ebignore file. These things were done. I also changed the decorator for the `viz.py/veteran_counts` function from get to post. This will ensure that it will fulfill requests coming from the backend. The documentation of the function was updated, as well. 
The notebook containing Sean's work is also now available in the repo, with this pull request.

## Fixes

Carried out fixes asked of by Associate DS Lead. 

Changed decorator for veteran_counts function.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change has a documentation update

## Change status
- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [X] I have pulled from master before submitting this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by bconn315 — COMMENTED** [review]
we could probably also add .csv files to the ignore

**Review by bconn315 — APPROVED** [review]
Looks great. thanks Keila

**Review by evangrinalds — APPROVED** [review]
Wow great work here. Thanks for the detailed PR.

**Comment by bconn315** [comment]
pushing commit

**Pull request closed without merging**
