### PR TITLE
Changes to visualization functions & figured out how to work with JSON files

### PR DESCRIPTION
**Pull request by keilayb**
# Description

Some changes had to be made to the visualization functions. `veteran_counts` was not handling JSON files properly. The changes to that function now fix that issue. For the moment, a JSON file has be saved somewhere, opened, read, and then worked with. Once we know the format that we will receive data from BE SQL queries, this function will have to edited further. The other visualization function, `vizmap`, was also having some issues. The file path was changed, and the parameters in `read_csv` had to change--ensuring that `zipcode` was a column in the DataFrame.

### Fixes 

JSON files are now properly handled by `veteran_counts` function properly. The `vizmap` function was not working. That bug was fixed.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [X] I have pulled from master before submitting this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by bconn315** [comment]
worked with Keila and confirm the json pull works to a dataframe for the plot.ly would be able to create a figure.

**Review by bconn315 — APPROVED** [review]
worked with Keila and confirm the json pull works to a dataframe for the plot.ly would be able to create a figure.

**Review by evangrinalds — APPROVED** [review]
Great work on handling the JSON files properly!

**Review by smdriggers — COMMENTED** [review]
The code is well linted and commented, easy to understand. In viz.py /veteran_counts it looks like that is a hardcoded test case. If that's so then a comment there mentioning that could help with clarity for other developers. 

Other than that it looks perfectly fine.

**Pull request merged**
